const WORKS = [
  {
    slug: "zmiana",
    title: "zmiana",
    image: "images/work-1.svg",
    technique: "akryl na płótnie",
    format: "100 × 80 cm",
    year: "2023",
  },
  {
    slug: "zmmmmmiana",
    title: "zmmmmmmmmmmmmiana",
    image: "images/work-2.svg",
    technique: "akryl na płótnie",
    format: "90 × 70 cm",
    year: "2022",
  },
  {
    slug: "fragment-pamieci-deszcz",
    title: "Fragment pamięci o deszczu",
    image: "images/work-3.svg",
    technique: "olej na płótnie",
    format: "120 × 100 cm",
    year: "2024",
  },
  {
    slug: "glosy-w-starym-lesie",
    title: "Głosy ukryte w starym lesie",
    image: "images/work-4.svg",
    technique: "akryl i tusz na płótnie",
    format: "80 × 60 cm",
    year: "2021",
  },
  {
    slug: "kolory-znikajace-o-zmroku",
    title: "Kolory znikające o zmroku",
    image: "images/work-5.svg",
    technique: "olej na płótnie",
    format: "70 × 70 cm",
    year: "2023",
  },
  {
    slug: "ruiny-marzen-pod-powiekami",
    title: "Ruiny marzeń pod powiekami",
    image: "images/work-6.svg",
    technique: "akryl na desce",
    format: "60 × 90 cm",
    year: "2020",
  },
  {
    slug: "echo-fal-w-ciemnej-wodzie",
    title: "Echo fal w ciemnej wodzie",
    image: "images/work-7.svg",
    technique: "olej na płótnie",
    format: "100 × 90 cm",
    year: "2022",
  },
  {
    slug: "swiatlo-miedzy-galeziami",
    title: "Światło między gałęziami",
    image: "images/work-8.svg",
    technique: "akryl na płótnie",
    format: "80 × 80 cm",
    year: "2023",
  },
  {
    slug: "cisza-po-burzy-piaskowej",
    title: "Cisza po burzy piaskowej",
    image: "images/work-9.svg",
    technique: "olej na desce",
    format: "90 × 70 cm",
    year: "2021",
  },
  {
    slug: "podroz-przez-mgliste-pole",
    title: "Podróż przez mgliste pole",
    image: "images/work-10.svg",
    technique: "akryl i tusz na płótnie",
    format: "110 × 90 cm",
    year: "2024",
  },
  {
    slug: "zapomniane-miasto-nocy",
    title: "Zapomniane miasto nocy",
    image: "images/work-11.svg",
    technique: "olej na płótnie",
    format: "100 × 100 cm",
    year: "2020",
  },
  {
    slug: "ostatni-promien-lata",
    title: "Ostatni promień lata",
    image: "images/work-12.svg",
    technique: "akryl na płótnie",
    format: "70 × 90 cm",
    year: "2023",
  },
];

